// <auto-generated />
using System;
using Easy_ManagerWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Easy_ManagerWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Easy_ManagerWeb.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_cliente");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endereco_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone_cliente");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.DadosUsuario", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_usuario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha_usuario");

                    b.HasKey("Usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_entrega");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_agendada");

                    b.Property<double?>("Distancia")
                        .HasColumnType("double")
                        .HasColumnName("distancia");

                    b.Property<DateTime>("DtCadastroEntrega")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro_entrega");

                    b.Property<int?>("OrcamentoId")
                        .HasColumnType("int")
                        .HasColumnName("id_orcamento");

                    b.Property<int?>("PacoteId")
                        .HasColumnType("int")
                        .HasColumnName("id_pacote");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tempo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tempo");

                    b.Property<double?>("ValorOrcamento")
                        .HasColumnType("double")
                        .HasColumnName("orcamento");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("PacoteId");

                    b.ToTable("entrega");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Gasto", b =>
                {
                    b.Property<int>("Id_Gasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_gasto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Gasto"));

                    b.Property<DateTime>("DataGasto")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_gasto");

                    b.Property<string>("Nm_Usuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nm_usuario");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("valor");

                    b.HasKey("Id_Gasto");

                    b.ToTable("gasto");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoPacote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Distancia")
                        .HasColumnType("double");

                    b.Property<string>("EnderecoCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PacoteId")
                        .HasColumnType("int");

                    b.Property<string>("Peso")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Tempo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ValorOrcamento")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PacoteId");

                    b.ToTable("Orcamentos", (string)null);
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pacote");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("peso");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tamanho");

                    b.HasKey("Id");

                    b.ToTable("pacote");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Entrega", b =>
                {
                    b.HasOne("Easy_ManagerWeb.Models.Cliente", "Cliente")
                        .WithMany("Entregas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("Easy_ManagerWeb.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId");

                    b.HasOne("Easy_ManagerWeb.Models.Pacote", "Pacote")
                        .WithMany("Entregas")
                        .HasForeignKey("PacoteId");

                    b.Navigation("Cliente");

                    b.Navigation("Orcamento");

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Orcamento", b =>
                {
                    b.HasOne("Easy_ManagerWeb.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Easy_ManagerWeb.Models.Pacote", "Pacote")
                        .WithMany()
                        .HasForeignKey("PacoteId");

                    b.Navigation("Cliente");

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Cliente", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("Easy_ManagerWeb.Models.Pacote", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
